### ISSUE TITLE
Berserk has no attribute 'Client'

### ISSUE THREAD

**Issue by ethicalhacker7192** [ZackClements/berserk#33]
* berserk version: 0.11.12
* Python version:3.11
* Operating System:Kali Linux

### Description

Describe what you were trying to get done.

I am a AI engineer, I was making a self learning AI for lichess that I could play against, but it ended up with this error.

Tell us what happened, what went wrong, and what you expected to happen.

I was going to test the AI, I expected it to well, work! But fate has a different plan as I get this freak error.

### What I Did

nothing, I just coded it and followed the guide and command guide and everything.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "/home/user/Desktop/ChessAI4/chessAI/agenttwo.py", line 794, in <module>
    agent = DQNAgent()
            ^^^^^^^^^^
  File "/home/user/Desktop/ChessAI4/chessAI/agenttwo.py", line 171, in __init__
    self.client = berserk.Client(berserk.TokenSession(self.token))
                  ^^^^^^^^^^^^^^
AttributeError: module 'berserk' has no attribute 'Client'
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt: 

```

**Comment by ethicalhacker7192** [comment]
actually, I just fixed it, but I am having issues with the streamer for moves, I can show you my code (I will censor my API tokens and everything though...)

**Comment by ethicalhacker7192** [comment]
Whoops, I forgot to close the issue.
